#import <Preferences/Preferences.h>
#import <CoreFoundation/CoreFoundation.h>
#import "RootListController.h"
#import "ColorPickerController.h"
#import "AnimationPickerController.h"
static NSString *const suite=@"com.mowang.kbglow"; static CFStringRef const note=CFSTR("com.mowang.kbglow.settingsChanged");
@implementation RootListController
- (NSArray*)specifiers { if(!_specifiers){ NSMutableArray*a=[NSMutableArray array]; [a addObject:[PSSpecifier groupSpecifierWithName:@"总开关"]]; [a addObject:[self sw:@"启用 KBGlow" key:@"enabled" def:YES]]; [a addObject:[PSSpecifier groupSpecifierWithName:@"启用键盘"]]; [a addObject:[self sw:@"微信输入法" key:@"wechatEnabled" def:YES]]; [a addObject:[self sw:@"百度输入法" key:@"baiduEnabled" def:YES]]; [a addObject:[self sw:@"搜狗输入法" key:@"sogouEnabled" def:YES]]; [a addObject:[PSSpecifier groupSpecifierWithName:@"发光效果"]]; PSSpecifier*x=[PSSpecifier preferenceSpecifierNamed:@"动画类型" target:nil set:nil get:nil detail:AnimationPickerController.class cell:PSLinkCell edit:nil]; [a addObject:x]; PSSpecifier*c=[PSSpecifier preferenceSpecifierNamed:@"发光颜色" target:nil set:nil get:nil detail:ColorPickerController.class cell:PSLinkCell edit:nil]; [a addObject:c]; [a addObject:[self slider:@"发光大小" key:@"glowSize" min:15 max:120 def:55]]; [a addObject:[self slider:@"动画时长" key:@"glowDuration" min:.1 max:1.5 def:.45]]; [a addObject:[self slider:@"发光强度" key:@"glowOpacity" min:.1 max:1 def:.75]]; [a addObject:[self sw:@"跟随手指位置" key:@"followFinger" def:YES]]; [a addObject:[PSSpecifier groupSpecifierWithName:@"说明"]]; [a addObject:[PSSpecifier preferenceSpecifierNamed:@"v1.2.1：保留原触摸出光机制，新增跟手移动与设置同步修复。" target:nil set:nil get:nil detail:nil cell:PSStaticTextCell edit:nil]]; _specifiers=a;} return _specifiers; }
- (PSSpecifier*)sw:(NSString*)n key:(NSString*)k def:(BOOL)v { PSSpecifier*s=[PSSpecifier preferenceSpecifierNamed:n target:self set:@selector(setV:specifier:) get:@selector(getV:) detail:nil cell:PSSwitchCell edit:nil]; [s setProperty:k forKey:@"key"]; [s setProperty:@(v) forKey:@"default"]; return s; }
- (PSSpecifier*)slider:(NSString*)n key:(NSString*)k min:(CGFloat)mn max:(CGFloat)mx def:(CGFloat)d { PSSpecifier*s=[PSSpecifier preferenceSpecifierNamed:n target:self set:@selector(setV:specifier:) get:@selector(getV:) detail:nil cell:PSSliderCell edit:nil]; [s setProperty:k forKey:@"key"]; [s setProperty:@(mn) forKey:@"minimumValue"]; [s setProperty:@(mx) forKey:@"maximumValue"]; [s setProperty:@(d) forKey:@"default"]; [s setProperty:@YES forKey:@"isContinuous"]; return s; }
- (void)setV:(id)v specifier:(PSSpecifier*)s { NSUserDefaults*d=[[NSUserDefaults alloc]initWithSuiteName:suite]; [d setObject:v forKey:[s propertyForKey:@"key"]]; [d synchronize]; CFPreferencesAppSynchronize((__bridge CFStringRef)suite); CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),note,NULL,NULL,true); }
- (id)getV:(PSSpecifier*)s { NSUserDefaults*d=[[NSUserDefaults alloc]initWithSuiteName:suite]; id v=[d objectForKey:[s propertyForKey:@"key"]]; return v?:[s propertyForKey:@"default"]; }
@end
